### PR TITLE
Add MiKTeX before tests run

### PR DESCRIPTION
**Pull request by CAMOBAP**
- #8

### CODE REVIEW

**Comment by ronaldtse** [comment]
@CAMOBAP795 failed tests...

**Comment by CAMOBAP** [comment]
@ronaldtse yep, MikTeX chocolatey package cannot be installed because of 404 looks like they cleaned their file server with installers, let's wait till https://chocolatey.org/packages/miktex becomes green

**Comment by ronaldtse** [comment]
@CAMOBAP795 I think Chocolatey MiKTeX will never be fixed -- the package is an auto-generated one, and the package source hasn't been updated in over a year:

https://github.com/aronovgj/choco-auto

Screen Shot 2019-05-05 at 7 51 07 AM

I also wrote to the MiKTeX author but have received no reply from him regarding maintaining a stable package link.

Now, apparently there is a official way of installing MiKTeX in an unattended way: https://miktex.org/announcement/miktex-setup-utility

It might be easiest for us to run this `miktexsetup` utility instead of the flaky/unstable Chocolatey package.

https://miktex.org/howto/deploy-miktex

> If you intend to install MiKTeX on many client computers, here is the recipe:

> 1. set up a local package repository on a server and share it in your organization
> 2. create a command script which silently installs MiKTeX from the local package repository
> 3. deploy MiKTeX by running the script on the client computers
> 4. Set up a local package repository

> 1. Get the MiKTeX Setup Utility for Windows:
> `wget https://miktex.org/download/win/miktexsetup-x64.zip`
> `unzip miktexsetup-x64.zip`

> 2. Run the setup utility on the server to set up the local package repository:
> `miktexsetup --verbose --local-package-repository=C:\temp\miktex --package-set=complete download`
> Depending on your Internet connection, this will take some time. When the command finishes, you have a local package repository in C:\temp\miktex. 

Then run,
`miktexsetup.exe --quiet --local-package-repository=C:\temp\miktex --package-set=basic install`

**Comment by ronaldtse** [comment]
@CAMOBAP795 this works. Thank you!

**Pull request merged**
