### PR TITLE
Feature/run test with miktex installed

### PR DESCRIPTION
**Pull request by CAMOBAP**
- #8

### CODE REVIEW

**Comment by ronaldtse** [comment]
@CAMOBAP795 thanks! Can you confirm that the `color` and `ntheorem` files will fail without MiKTeX installed? Thanks!

**Comment by CAMOBAP** [comment]
@ronaldtse, unfortunately, it works absolutely the same way with or without MiKTeX

**Comment by ronaldtse** [comment]
@camobap795 there are some features in those two packages that trigger an include of the TeX distribution. Can you investigate the LaTeXML code to see which features of those packages require the external TeX distribution? Thanks.

**Comment by CAMOBAP** [comment]
@ronaldtse sure

**Comment by ronaldtse** [comment]
Ping @CAMOBAP795

**Pull request closed without merging**
